; PlatformIO Project Configuration File

[env]
test_framework = googletest

[env:rymcu-esp32-s3-devkitc-1]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:native]
platform = platformio/native
build_unflags = -std=gnu++11
build_flags = -std=gnu++17 -Iinclude
test_filter = native/*
